var json = {
	"movie1": {
		"genre": ["Genre: ", "Sci-Fi / Fantacy"],
		"title": ["Title: ", "The Matrix"],
		"rating": ["Rating: ", "10"],
		"status": ["Status: ", "In"],	
	},
	"movie2": {
		"genre": ["Genre: ", "Comedy"],
		"title": ["Title: ", "The 40 Year Old Virgin"],
		"rating": ["Rating: ", "8"],
		"status": ["Status: ", "In"],	
	},
	"movie3": {
		"genre": ["Genre: ", "Drama"],
		"title": ["Title: ", "The American President"],
		"rating": ["Rating: ", "7"],
		"status": ["Status: ", "In"],	
	},
	"movie4": {
		"genre": ["Genre: ", "Drama"],
		"title": ["Title: ", "August Rush"],
		"rating": ["Rating: ", "7"],
		"status": ["Status: ", "In"],	
	},
	"movie5": {
		"genre": ["Genre: ", "Action Adventure"],
		"title": ["Title: ", "Avatar"],
		"rating": ["Rating: ", "10"],
		"status": ["Status: ", "In"],	
	},
	"movie6": {
		"genre": ["Genre: ", "Action Adventure"],
		"title": ["Title: ", "Captain America"],
		"rating": ["Rating: ", "8"],
		"status": ["Status: ", "In"],	
	},
	"movie7": {
		"genre": ["Genre: ", "Action Adventure"],
		"title": ["Title: ", "The Book of Eli"],
		"rating": ["Rating: ", "9"],
		"status": ["Status: ", "In"],	
	},
	"movie8": {
		"genre": ["Genre: ", "Kids and Family"],
		"title": ["Title: ", "Cars 2"],
		"rating": ["Rating: ", "8"],
		"status": ["Status: ", "In"],
	},
	"movie9": {
		"genre": ["Genre: ", "Kids and Family"],
		"title": ["Title: ", "Alvin and the Chipmunks: Chipwrecked"],
		"rating": ["Rating: ", "6"],
		"status": ["Status: ", "In"],
	},
	"movie10": {
		"genre": ["Genre: ", "Romance"],
		"title": ["Title: ", "Dan In Real Life"],
		"rating": ["Rating: ", "9"],
		"status": ["Status: ", "In"],		
	},
	"movie11": {
		"genre": ["Genre: ", "Horror"],
		"title": ["Title: ", "I Am Lengend"],
		"rating": ["Rating: ", "6"],
		"status": ["Status: ", "In"],		
	},
	"movie12": {
		"genre": ["Genre: ", "Kids and Family"],
		"title": ["Title: ", "Dr. Seuss' The Lorax"],
		"rating": ["Rating: ", "8"],
		"status": ["Status: ", "In"],		
	},
	"movie13": {
		"genre": ["Genre: ", "Sci-Fi / Fantacy"],
		"title": ["Title: ", "The Matrix Reloaded"],
		"rating": ["Rating: ", "9"],
		"status": ["Status: ", "In"],		
	},
	"movie14": {
		"genre": ["Genre: ", "Sci-Fi / Fantacy"],
		"title": ["Title: ", "The Matrix Revolutions"],
		"rating": ["Rating: ", "9"],
		"status": ["Status: ", "In"],	
	},
	"movie15": {
		"genre": ["Genre: ", "Comedy"],
		"title": ["Title: ", "The Rocker"],
		"rating": ["Rating: ", "9"],
		"status": ["Status: ", "In"],
	},
	"movie16": {
		"genre": ["Genre: ", "Thriller"],
		"title": ["Title: ", "Signs"],
		"rating": ["Rating: ", "8"],
		"status": ["Status: ", "In"],	
	},
	"movie17": {
		"genre": ["Genre: ", "Sci-Fi / Fantacy"],
		"title": ["Title: ", "The Animatrix"],
		"rating": ["Rating: ", "8"],
		"status": ["Status: ", "In"],	
	},
	"movie18": {
		"genre": ["Genre: ", "Romance"],
		"title": ["Title: ", "The Vow"],
		"rating": ["Rating: ", "8"],
		"status": ["Status: ", "In"],	
	},
	"movie19": {
		"genre": ["Genre: ", "Thriller"],
		"title": ["Title: ", "The DaVinci Code"],
		"rating": ["Rating: ", "7"],
		"status": ["Status: ", "In"],	
	},
	"movie20": {
		"genre": ["Genre: ", "Drama"],
		"title": ["Title: ", "Shall We Dance"],
		"rating": ["Rating: ", "7"],
		"status": ["Status: ", "In"],
	}
}